### ISSUE TITLE
[BUG] Published version (1.6.2) seem to not include changes.

### ISSUE THREAD

**Issue by egmacke** [jun-sheaf/ts-japi#45]
## Describe the bug<sup>*</sup>

Using v1.6.2 from npm, the pulled package doesn't appear to include the changes for that version.

## To Reproduce<sup>*</sup>

- Create a new project
- Add `ts-japi: 1.6.2` as a dependecy
- Check the lib files in the node_modules folder
- The `relatedName` field in `RelatorOptions` is not included

## Expected behavior<sup>*</sup>

Should include the changes from this commit: c5a8201184e5c63c919c812595e7c6a9b895ea55

## Platform<sup>*</sup>

- [x] OS: {{ Write the OS name and its version }}
- [x] Browser {{ Write the browser name and its version }}
- [x] Version: {{ Write the package version }}

**Comment by jrandolf** [comment]
Should be fixed now.
