### ISSUE TITLE
[BUG] incorrectly only a single include resources

### ISSUE THREAD

**Issue by basz** [jun-sheaf/ts-japi#68]
## Describe the bug<sup>\*</sup>

I'm not receiving all includes rources for a compount document

## To Reproduce<sup>\*</sup>

given a model like related like so

user - one2many > preferences
user - one2many > member-organisations - o2o -> organisation

I have a fully loaded model for a single user, which has 3 member-organisations which each have an organisation.

In my serialised output I only see a single included organisation.

I am using include: ['organisation-members', 'preferences', 'organisation-members.organisation'] as serializer options.

If'v noticed adding `organisation-members.organisation.` as an additional (note the trailing dot) argument I will get two organisations included (but still not 3)...

## Expected behavior<sup>\*</sup>

All resources should be included

https://gist.github.com/basz/71e9296d468c867757ee7f8eee80677d

**Comment by egmacke** [comment]
I've had a look into what's going on and I'm pretty sure I've isolated the issue. It's related to how the serializer determines whether to recurse deeper, and I think there's a flaw in the logic.

Putting together a possible fix now.
