### ISSUE TITLE
[BUG] Incorrect license in docs

### ISSUE THREAD

**Issue by grempe** [jun-sheaf/ts-japi#8]
## Describe the bug<sup>*</sup>

The documentation page still shows the license as Gnu Affero in the badge at the top as well as in the footer. Since the license has been changed to Apache 2.0 this should be changed to reflect that as well.

https://jun-sheaf.github.io/ts-japi/index.html

## To Reproduce<sup>*</sup>

Open: https://jun-sheaf.github.io/ts-japi/index.html

## Expected behavior<sup>*</sup>

See the correct license.

## Platform<sup>*</sup>

- [ ] OS: {{ Write the OS name and its version }}
- [X] Browser ALL
- [ ] Version: {{ Write the package version }}

**Comment by jun-sheaf** [comment]
Thanks for the issue.

I just haven't gotten around to updating the docs with the license. It has been updated along with devDependencies.
